language: generic
sudo: false
cache: apt

os:
  - linux
  - osx

env:
  global: LANGUAGE=C++ CXX=g++-5 CC=gcc-5
  matrix:
    - BUILD_COMMAND="./build.sh"
    - BUILD_COMMAND="./build_lookup.sh"

addons:
  apt:
    packages:
      - g++-5
      - libboost-all-dev
      - libleveldb-dev
      - libjsoncpp-dev
      - libsnappy-dev
      - curl
      - libargtable2-dev
      - libhiredis-dev
    sources: &sources
      - r-packages-trusty
      - llvm-toolchain-trusty
      - ubuntu-toolchain-r-test
      - llvm-toolchain-trusty-5.0

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install pkg-config jsoncpp leveldb; fi

script:
  - (eval "$BUILD_COMMAND")
  - ctest

# TODO: fix the travis build failure on osx
matrix:
  allow_failures:
    - os: osx

install:
  - wget -c http://ftp.gnu.org/gnu/libmicrohttpd/libmicrohttpd-0.9.59.tar.gz
  - (tar zxf libmicrohttpd-0.9.59.tar.gz; cd libmicrohttpd-0.9.59; ./configure; make; sudo make install; cd ..; rm -fr libmicrohttpd-0.9.59)
  - wget -O libjson-rpc-cpp-1.1.0.tar.gz https://github.com/cinemast/libjson-rpc-cpp/archive/v1.1.0.tar.gz
  - (tar xzf libjson-rpc-cpp-1.1.0.tar.gz; cd libjson-rpc-cpp-1.1.0; cmake . && make; sudo make install; sudo ldconfig; cd ..; rm -fr libjson-rpc-cpp-1.1.0)
